required = [
	"golang.org/x/tools/cmd/guru"
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/ugorji/go"
  branch = "master"

[[constraint]]
  name = "github.com/urfave/cli"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

[[constraint]]
  branch = "master"
  name = "kuroku.io/margocode"

[[constraint]]
  name = "github.com/rogpeppe/go-internal"
  version = "1.3.0"
